import type { NextConfig } from "next";

const withPWA = require("next-pwa")({
  dest: "public",
  disable: process.env.NODE_ENV === "development",
  register: false, // we register manually (more control / fewer surprises)
  skipWaiting: true,
  clientsClaim: true,
  cacheOnFrontEndNav: true, // cache pages during client-side navigation
  fallbacks: {
    document: "/offline", // show offline page when a page can't be fetched
  },
  // These runtime rules are in addition to the precache manifest generated by next-pwa.
  runtimeCaching: [
    // 1. RSC Data (for smooth link navigation)
    {
      urlPattern: ({ url, request }: { url: URL; request?: any }) => {
        if (url.origin !== self.location.origin) return false;
        const isRsc = url.search.includes("_rsc") ||
          (request && request.headers && request.headers.get && request.headers.get("RSC") === "1");
        return isRsc;
      },
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "pages-rsc-v4",
        expiration: {
          maxEntries: 1500,
          maxAgeSeconds: 60 * 60 * 24 * 30,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
        matchOptions: {
          ignoreSearch: true,
        },
      },
    },
    // 2. HTML Pages (for direct entry / refresh)
    {
      urlPattern: ({ url, request }: { url: URL; request?: any }) => {
        if (url.origin !== self.location.origin) return false;
        const p = url.pathname;
        const isRsc = url.search.includes("_rsc") ||
          (request && request.headers && request.headers.get && request.headers.get("RSC") === "1");
        const isPage = p === "/" || p.startsWith("/hymn/") || p === "/offline" || p === "/contribute";
        return isPage && !isRsc;
      },
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "pages-html-v4",
        expiration: {
          maxEntries: 1500,
          maxAgeSeconds: 60 * 60 * 24 * 30,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
        matchOptions: {
          ignoreSearch: true,
        },
      },
    },
    // 3. PWA Metadata (Manifest, Favicon, Icons)
    {
      urlPattern: ({ url }: { url: URL }) => {
        if (url.origin !== self.location.origin) return false;
        const p = url.pathname;
        return p.includes("manifest") || p.includes("favicon") || p.includes("icon") || p.endsWith(".ico");
      },
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "pwa-metadata-v4",
        expiration: {
          maxEntries: 50,
        },
      },
    },
    // 4. Sheet Music images
    {
      urlPattern: ({ url }: { url: URL }) => {
        return url.origin === self.location.origin && url.pathname.includes("/sheets/fil/");
      },
      handler: "CacheFirst",
      options: {
        cacheName: "sheet-images-v4",
        expiration: {
          maxEntries: 5000,
          maxAgeSeconds: 60 * 60 * 24 * 365,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    // 5. Next.js Static Assets
    {
      urlPattern: ({ url }: { url: URL }) => {
        return url.origin === self.location.origin && url.pathname.startsWith("/_next/static/");
      },
      handler: "CacheFirst",
      options: {
        cacheName: "static-assets-v4",
        expiration: {
          maxEntries: 1000,
        },
      },
    },
  ],
});

const nextConfig: NextConfig = {
  // next-pwa configures webpack internally. Next 16 enables Turbopack by default
  // and will error if a webpack config is present without a turbopack config.
  turbopack: {},
};

export default withPWA(nextConfig);
