import type { NextConfig } from "next";

const withPWA = require("next-pwa")({
  dest: "public",
  disable: process.env.NODE_ENV === "development",
  register: false, // we register manually (more control / fewer surprises)
  skipWaiting: true,
  clientsClaim: true,
  // These runtime rules are in addition to the precache manifest generated by next-pwa.
  runtimeCaching: [
    // Sheet music PNGs (static assets served from /public/sheets/fil/*)
    {
      urlPattern: /^\/sheets\/fil\/.*\.png$/i,
      handler: "CacheFirst",
      options: {
        cacheName: "sheet-images",
        expiration: {
          maxEntries: 5000,
          maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    // Next.js data / pages (best-effort offline navigation after first load)
    {
      urlPattern: /^\/(_next\/data\/.*|hymn\/.*|hymn\/.*\/sheet\/?)$/i,
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "pages-and-data",
        expiration: {
          maxEntries: 500,
          maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    // Next static assets
    {
      urlPattern: /^\/_next\/static\/.*/i,
      handler: "CacheFirst",
      options: {
        cacheName: "next-static",
        expiration: {
          maxEntries: 500,
          maxAgeSeconds: 60 * 60 * 24 * 365,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    // Other same-origin requests (keep conservative to avoid caching POSTs, etc.)
    {
      urlPattern: ({ url }: { url: URL }) => url.origin === self.location.origin,
      handler: "NetworkFirst",
      options: {
        cacheName: "same-origin",
        networkTimeoutSeconds: 5,
        expiration: {
          maxEntries: 200,
          maxAgeSeconds: 60 * 60 * 24 * 7,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
  ],
});

const nextConfig: NextConfig = {
  // next-pwa configures webpack internally. Next 16 enables Turbopack by default
  // and will error if a webpack config is present without a turbopack config.
  turbopack: {},
};

export default withPWA(nextConfig);
